### ISSUE TITLE
[ Discussion ] ImmutableCollections or just ReadOnlyCollections?

### ISSUE THREAD

**Issue by renanrcp** [MariBotOfficial/MariCommands#6]
Hello guys, I will start a discussion here about if we will continue using ImmutableCollections.

**ReadOnlyCollections v.s ImmutableCollections:**

**ReadOnlyCollections:**
 You can't change any value of this collection directly, but when you create this collection type you pass the values, if the "original values" changes this collection will be changed too.

**ImmutableCollections:**
Your values will never change after created, but it will allocate more memory (will "dupe" the original values).

**Here a discussion to why use Immutable:**
[Discussion 1](https://stackoverflow.com/questions/30165810/why-use-immutablelist-over-readonlycollection)

**And here why not based in memory allocation:**
[Docs 1](https://docs.microsoft.com/en-us/archive/msdn-magazine/2017/march/net-framework-immutable-collections#performance-and-memory-consumption-of-immutable-collections)

What is your opinion about this?

**Comment by pedro-lb** [comment]
Based on this answer

![image](https://user-images.githubusercontent.com/22061051/84599370-e53b4800-ae47-11ea-812c-73887f5ce0aa.png)


Do we have any thread related problems? If our code needs to be thread safe, we'll need to use ImmutableCollections. Otherwise we can use ReadOnlyCollections.

**Comment by renanrcp** [comment]
> Based on this answer
> 
> ![image](https://user-images.githubusercontent.com/22061051/84599370-e53b4800-ae47-11ea-812c-73887f5ce0aa.png)
> 
> Do we have any thread related problems? If our code needs to be thread safe, we'll need to use ImmutableCollections. Otherwise we can use ReadOnlyCollections.

Oh yes this lib is for a lot of threads too.

**Comment by pedro-lb** [comment]
So ImmutableCollections it is

**Comment by renanrcp** [comment]
I think at this point of the project we can close this, ty for all opinions we stayed with ImmutableCollections
